# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/AREA184/Desktop/gameplane/project_2.srcs/sources_1/ip/ufo_rom/ufo_rom.xci
# IP: The module: 'ufo_rom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/AREA184/Desktop/gameplane/project_2.srcs/sources_1/ip/ufo_rom/ufo_rom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ufo_rom'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/AREA184/Desktop/gameplane/project_2.srcs/sources_1/ip/ufo_rom/ufo_rom.xci
# IP: The module: 'ufo_rom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/AREA184/Desktop/gameplane/project_2.srcs/sources_1/ip/ufo_rom/ufo_rom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ufo_rom'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
